smwds/frontend/views.py
from flask import Blueprint, render_template, current_app, request, flash, \
    url_for, redirect, session, abort, g
from flask_login import login_user, logout_user, current_user, login_required
from frontend.form import LoginForm
from api.views import get_toplogy
from user import User
from extensions import cache
from node import Indb_func
import uuid
import hashlib
import requests
from utils import github
from flask_socketio import (
    send,
    SocketIO,
    emit,
    disconnect,
    join_room
)

frontend = Blueprint('frontend', __name__, template_folder='../templates')

#frontend = Blueprint('frontend', __name__)
'''
### DOC ###

frontend pages 
/index

'''


@frontend.before_request
def frontend_before_request():
    current_app.logger.info(str(current_user.name) + "@uid:" + str(current_user.id) +
                            " @session:" + session.session_id + " @request_url:" + request.url + " @IP:" + ret_ip())
    g.user = current_user


@frontend.teardown_request
def frontend_teardown_request(extensions):
    pass


@frontend.route('/testcache')
@cache.memoize(timeout=60 * 20)
def testcache():
    name = 'mink'
    return name + " " + str(cache.get('testcache'))


def ret_ip():
    if request.headers.getlist("X-Forwarded-For"):
        string_ip = request.headers.getlist("X-Forwarded-For")[0]
        t_ip = str(string_ip).split(',')[0]
    else:
        t_ip = request.remote_addr
    #print(t_ip)
    return str(t_ip)
'''

deprecated function for updating main page

'''

def ret_index():
    #r = requests.get("http://127.0.0.1:8080/api/v1/indb/24/Ali.master.cn00/graphite/memory_percent_usedWOBuffersCaches")
    #r = Indb_func.monitor_data(
    #    table='memory_percent_usedWOBuffersCaches', db='graphite', node='Ali.master.cn00')
    #p = Indb_func.monitor_data(
    #    table='cpu_user', db='graphite', node='Ali.master.cn00')
    index_data = {
        #'top': get_toplogy(),
        'user': {
            'name': session['username'],
            'remember_me': session['remember_me'],
            'ip': ret_ip()
        }
       # 'mem': r,
       # 'cpu': p
    }
    current_app.logger.info(index_data)
    return index_data



@frontend.route('/main')
@login_required
#@cache.memoize(timeout=100)
def index():
    s_id = request.args.get('s_id')
    if s_id == None:
        return redirect(url_for('frontend.login'))
    check_id = hashlib.md5(str(session['uid']).encode('utf-8')).hexdigest()
    if s_id == check_id:
        return render_template('index.html', index_data=ret_index())
    else:
        current_app.logger.warning(
            "Session invaild : " + str(s_id) + ' != ' + check_id)
        return redirect(url_for('frontend.logout'))

@frontend.route('/github')
def github_login():
    redirect_uri = url_for('frontend.github_authorized', _external=True)
    print(redirect_uri)
    # More scopes http://developer.github.com/v3/oauth/#scopes
    params = {'redirect_uri': redirect_uri, 'scope': 'user:email'} 
    print(github.get_authorize_url(**params))
    return redirect(github.get_authorize_url(**params))


# same path as on application settings page
@frontend.route('/gcb')
def github_authorized():
    # check to make sure the user authorized the request
    if not 'code' in request.args:
        flash('You did not authorize the request')
        return render_template('info.html'), 200
    # make a request for the access token credentials using code
    redirect_uri = url_for('frontend.github_authorized', _external=True)
    data = dict(code=request.args['code'],
        redirect_uri=redirect_uri,
        scope='user:email,user')
    try:
        auth = github.get_auth_session(data=data)
        session['token'] = auth.access_token
        # the "me" response
        me = auth.get('user').json()
    except Exception as e:
        flash(str(e))
        return render_template('info.html'), 200
    user = User.get_or_create(me)
    login_user(user)
    session['sid'] = hashlib.md5(str(user.id).encode('utf-8')).hexdigest()
    session['username'] = user.name
    return redirect(url_for('frontend.start', s_id=session['sid']))

@frontend.route('/page')
@login_required
def start():
    index_data = {
        'user': {
            'name': session['username'],
            'ip': ret_ip()
        }
    }
    return render_template('index.html', index_data=index_data)

@frontend.route('/')
@frontend.route('/login', methods=['GET', 'POST'])
def login():
    # if g.user is not None and g.user.is_authenticated:
    #    return redirect(url_for('frontend.index'))
    return render_template('info.html'), 200

    form = LoginForm()

    if form.validate_on_submit():

        session['remember_me'] = form.remember_me.data
        #user = User.query.filter_by(name=form.name.data.lower()).first()
        user, auth = User.authenticate(form.name.data, form.password.data)
        if user and auth:
            current_app.logger.info(
                form.name.data + ' checked in with data: ' + str(form.remember_me.data))
            session['username'] = form.name.data
            session['log in'] = True
            session['uid'] = str(user.id)
            session['sid'] = hashlib.md5(
                str(user.id).encode('utf-8')).hexdigest()
            login_user(user, remember=session['remember_me'])
            # current_app.logger.info(str(session))
            return redirect(url_for('frontend.index', s_id=session['sid']))
        else:
            current_app.logger.warning(
                'user ' + form.name.data + ' failed with authentication')
            return render_template('login.html', form=form, failed_auth=True)

    return render_template('login.html', form=form), 200

#@frontend.route('/test/', methods=['POST'])
# def test():
#    data = request.json
#    print(str(data))
#    emit('connect', data, room = '1', namespace='/test')
#    return 'ok',200


@frontend.route('/logout')
def logout():

    logout_user()
    return redirect(url_for('frontend.login'))


@frontend.route('/closed')
@login_required
def closed():

    return render_template('closed.html', index_data=ret_index())

smwds/templates/invoice_print.html
<!DOCTYPE html>
<html>

<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <title>INSPINIA | Invoice Print</title>

    <link href="css/bootstrap.min.css" rel="stylesheet">
    <link href="font-awesome/css/font-awesome.css" rel="stylesheet">

    <link href="css/animate.css" rel="stylesheet">
    <link href="css/style.css" rel="stylesheet">

</head>

<body class="white-bg">
                <div class="wrapper wrapper-content p-xl">
                    <div class="ibox-content p-xl">
                            <div class="row">
                                <div class="col-sm-6">
                                    <h5>From:</h5>
                                    <address>
                                        <strong>Inspinia, Inc.</strong><br>
                                        106 Jorg Avenu, 600/10<br>
                                        Chicago, VT 32456<br>
                                        <abbr title="Phone">P:</abbr> (123) 601-4590
                                    </address>
                                </div>

                                <div class="col-sm-6 text-right">
                                    <h4>Invoice No.</h4>
                                    <h4 class="text-navy">INV-000567F7-00</h4>
                                    <span>To:</span>
                                    <address>
                                        <strong>Corporate, Inc.</strong><br>
                                        112 Street Avenu, 1080<br>
                                        Miami, CT 445611<br>
                                        <abbr title="Phone">P:</abbr> (120) 9000-4321
                                    </address>
                                    <p>
                                        <span><strong>Invoice Date:</strong> Marh 18, 2014</span><br/>
                                        <span><strong>Due Date:</strong> March 24, 2014</span>
                                    </p>
                                </div>
                            </div>

                            <div class="table-responsive m-t">
                                <table class="table invoice-table">
                                    <thead>
                                    <tr>
                                        <th>Item List</th>
                                        <th>Quantity</th>
                                        <th>Unit Price</th>
                                        <th>Tax</th>
                                        <th>Total Price</th>
                                    </tr>
                                    </thead>
                                    <tbody>
                                    <tr>
                                        <td><div><strong>Admin Theme with psd project layouts</strong></div>
                                            <small>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</small></td>
                                        <td>1</td>
                                        <td>$26.00</td>
                                        <td>$5.98</td>
                                        <td>$31,98</td>
                                    </tr>
                                    <tr>
                                        <td><div><strong>Wodpress Them customization</strong></div>
                                            <small>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
                                                Eiusmod tempor incididunt ut labore et dolore magna aliqua.
                                            </small></td>
                                        <td>2</td>
                                        <td>$80.00</td>
                                        <td>$36.80</td>
                                        <td>$196.80</td>
                                    </tr>
                                    <tr>
                                        <td><div><strong>Angular JS & Node JS Application</strong></div>
                                            <small>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</small></td>
                                        <td>3</td>
                                        <td>$420.00</td>
                                        <td>$193.20</td>
                                        <td>$1033.20</td>
                                    </tr>

                                    </tbody>
                                </table>
                            </div><!-- /table-responsive -->

                            <table class="table invoice-total">
                                <tbody>
                                <tr>
                                    <td><strong>Sub Total :</strong></td>
                                    <td>$1026.00</td>
                                </tr>
                                <tr>
                                    <td><strong>TAX :</strong></td>
                                    <td>$235.98</td>
                                </tr>
                                <tr>
                                    <td><strong>TOTAL :</strong></td>
                                    <td>$1261.98</td>
                                </tr>
                                </tbody>
                            </table>
                            <div class="well m-t"><strong>Comments</strong>
                                It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less
                            </div>
                        </div>

    </div>

    <!-- Mainly scripts -->
    <script src="js/jquery-2.1.1.js"></script>
    <script src="js/bootstrap.min.js"></script>
    <script src="js/plugins/metisMenu/jquery.metisMenu.js"></script>

    <!-- Custom and plugin javascript -->
    <script src="js/inspinia.js"></script>

    <script type="text/javascript">
        window.print();
    </script>

</body>

</html>

smwds/templates/menu.html
<!DOCTYPE html>
<html>

<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <title>Deyun.io</title>

    <link href="css/bootstrap.min.css" rel="stylesheet">
    <link href="font-awesome/css/font-awesome.css" rel="stylesheet">
    <!--<link href="css/animate.css" rel="stylesheet">-->
    <link href="css/animate-2.css" rel="stylesheet">
    <link href="css/style.css" rel="stylesheet">
    <!--<link href="css/plugins/dataTables/datatables.min.css" rel="stylesheet">-->
    <!-- FooTable -->
    <link href="css/plugins/footable/footable.core.css" rel="stylesheet">
    <!--<link href="js/plugins/footable-standalone.latest/css/footable.standalone.css" rel="stylesheet">-->
    <!--<link href="css/plugins/toastr/toastr.min.css" rel="stylesheet">-->


</head>

<body class="top-navigation">

    <div id="wrapper">
        <div id="page-wrapper" class="gray-bg">
        <div class="row border-bottom white-bg">
        <nav class="navbar navbar-fixed-top" role="navigation">
            <div class="navbar-header">
                {% cache 60*5 %}
                <button aria-controls="navbar" aria-expanded="false" data-target="#navbar" data-toggle="collapse" class="navbar-toggle collapsed" type="button">
                    <i class="fa fa-reorder"></i>
                </button>
                <a class="navbar-brand">Deyun.io</a>
            </div>
            {% set active_page = active_page|default('index') %}
            <div class="navbar-collapse collapse" id="navbar">
                <ul class="nav navbar-nav">
                    <li class="active">
                        <a aria-expanded="false" role="button" href="index.html"> Main </a>
                    </li>
                    <li class="dropdown">
                        <a aria-expanded="false" role="button" href="index.html#" class="dropdown-toggle" data-toggle="dropdown"> Asset Manager <span class="caret"></span></a>
                        <ul role="menu" class="dropdown-menu">
                            <li><a href="{{ url_for('frontend.closed') }}" >Toplogy</a></li>
                            <li><a href="{{ url_for('frontend.closed') }}">List</a></li>
                            <li><a href="{{ url_for('frontend.closed') }}">Search</a></li>
                            <li><a href="{{ url_for('frontend.closed') }}">Service</a></li>
                        </ul>
                    </li>
                    <li class="dropdown">
                        <a aria-expanded="false" role="button" href="index.html#" class="dropdown-toggle" data-toggle="dropdown"> Monitor <span class="caret"></span></a>
                        <ul role="menu" class="dropdown-menu">
                            <li><a href="{{ url_for('frontend.closed') }}">Perf</a></li>
                            <li><a href="{{ url_for('frontend.closed') }}">Event</a></li>
                            <li><a href="{{ url_for('frontend.closed') }}">Log</a></li>
                            <li><a href="{{ url_for('frontend.closed') }}">Http</a></li>
                        </ul>
                    </li>
                    <li class="dropdown">
                        <a aria-expanded="false" role="button" href="index.html#" class="dropdown-toggle" data-toggle="dropdown"> State <span class="caret"></span></a>
                        <ul role="menu" class="dropdown-menu">
                            <li><a href="{{ url_for('frontend.closed') }}">Apply</a></li>
                            <li><a href="{{ url_for('frontend.closed') }}">History</a></li>
                            <li><a href="{{ url_for('frontend.closed') }}">New</a></li>
                            <li><a href="{{ url_for('frontend.closed') }}">Run CMD</a></li>
                        </ul>
                    </li>
                    <li class="dropdown">
                        <a aria-expanded="false" role="button" href="index.html#" class="dropdown-toggle" data-toggle="dropdown"> Settings <span class="caret"></span></a>
                        <ul role="menu" class="dropdown-menu">
                            <li><a href="{{ url_for('frontend.closed') }}">Node Register</a></li>
                            <li><a href="{{ url_for('frontend.closed') }}">Master Manager</a></li>
                            <li><a href="{{ url_for('frontend.closed') }}">SSH Auth</a></li>
                            <li><a href="{{ url_for('frontend.closed') }}">User Profile</a></li>
                        </ul>
                    </li>

                </ul>
                <ul class="nav navbar-top-links navbar-right">
                    <li>
                        <a href="{{ url_for('frontend.logout') }}">
                            <i class="fa fa-sign-out"></i> Log out
                        </a>
                    </li>
                </ul>       
                {% endcache %}
                {% include "sidebar.html" %}
            </div>
        </nav>
        </div>


         <!-- Mainly scripts -->
    <script src="js/jquery-2.1.1.js"></script>
    <script src="js/bootstrap.min.js"></script>
    <script src="js/plugins/metisMenu/jquery.metisMenu.js"></script>
    <script src="js/plugins/slimscroll/jquery.slimscroll.min.js"></script>

    <!-- Custom and plugin javascript -->
    <script src="js/inspinia.js"></script>
    <script src="js/plugins/pace/pace.min.js"></script>

    <!-- Flot -->
    <script src="js/plugins/flot/jquery.flot.js"></script>
    <script src="js/plugins/flot/jquery.flot.tooltip.min.js"></script>
    <script src="js/plugins/flot/jquery.flot.spline.js"></script>
    <script src="js/plugins/flot/jquery.flot.resize.js"></script>
    <script src="js/plugins/flot/jquery.flot.pie.js"></script>
    <script src="js/plugins/flot/jquery.flot.symbol.js"></script>
    <script src="js/plugins/flot/jquery.flot.time.js"></script>

    <!-- ChartJS-->
    <!--<script src="js/plugins/chartJs/Chart.min.js"></script>-->
    <script src="js/plugins/chartJs/Chart.min23.js"></script>
    <!-- Peity -->
    <script src="js/plugins/peity/jquery.peity.min.js"></script>
    <!-- Peity demo -->
    <script src="js/demo/peity-demo.js"></script>

        <!-- Sparkline -->
    <script src="js/plugins/sparkline/jquery.sparkline.min.js"></script>

    <!--<script src="js/plugins/dataTables/datatables.min.js"></script>-->
    <script src="js/plugins/footable/footable.all.min.js"></script>
    <!--<script src="js/plugins/footable-standalone.latest/js/footable.js"></script>-->
    <!--raphael and cloudrelation-->
    <script src="js/plugins/cloudrelation/raphael.js"></script>

    <script src="js/plugins/cloudrelation/cloudRelation.js"></script>

    <script src="js/plugins/cytoscape/cytoscape.js"></script>
    <!--dagra 0.74-->
    <script src="js/dagre.min.js"></script>
    <!--cytoscape-dagre 1.12-->
    <script src="js/cytoscape-dagre.js"></script>
    <!--socketio 1.35-->
    <script type="text/javascript" src="js/socket.io.min.js"></script>
    <script src="js/data.js" ></script>
    <!--listjs-->
    <script src="js/list.js"></script>
    <script src="js/list.pagination.min.js"></script>
    <!--prettyprint.js-->
    <script src="js/prettyprint.js"></script>
    <!--Notification script-->
    <!--<script src="js/plugins/toastr/toastr.min.js"></script>-->
    <script src="js/bootstrap-notify.min.js"></script>

            
        {% block content %}{% endblock %}
    

    
    <script type="text/javascript" charset="utf-8">
        $(document).ready(function() {
            var mltask = 0;
            var mlexec = 0;
            var mloptions = {
                  valueNames: ['ml_title', 'ml_progress_info','ml_info', 'ml_progress',{ attr: 'data-jid', name: 'jid' }],
                  //<div style="width: 22%;"class="progress-bar progress-bar-warning"></div> <button class="ml_test">Test button></button>
                 item: '<li><a><div class="small  pull-left m-t-xs media-body"><h4 class=" text-center ml_title jid" data-jid="23456"></h4><p class="ml_info"></p></div><div class="small ml_progress_info"></div><div class="progress progress-mini ml_progress"></div></a></li>',
                 page:50
                 /*plugins: [
                       ListPagination({})
                     ]*/
                };
                //warning-element info-element success-element
            //var mlvalues = [{ml-title:'System initialization completed'}, {ml-info: ''}, {ml-progress:''}];
            var mlvalues = [{
                jid:'111222',
                ml_title: 'Jonny Strömberg',
                ml_progress_info: 'ETA : 5 minutes',
                ml_info: '1986+asdasdasdsadasdsa very long descriptyion very long descriptyion very long descriptyion very long descriptyion',
                ml_progress: '<div style="width: 22%;"class="progress-bar progress-bar-warning"></div>'
              },
              {
                jid:'222333',
                ml_title: 'Jonas Arnklint',
                ml_progress_info: 'ETA : 5 minutes',
                ml_info: '1985+asdasdasdasd........................................',
                ml_progress: '<div style="width: 22%;"class="progress-bar progress-bar-warning"></div>'
              }];
            var menuList = new List('menu-list', mloptions); 
            $('.ml_test').click(function() {
            var itemId = $(this).closest('li').find('.jid').attr('data-jid');
            console.log(menuList.get("jid","1"));
            });

            socket.on('salt_task_menu', function(msg) {
                update_menulist(msg);
                //console.log( document.getElementById('menu-list'));
                //socket.emit('my_event', {data: 'I\'m connected!'});
                //console.log('I\'m connected! :' + msg);
            });
            socket.on('sitestatus', function(msg) {
                //console.log('sitestatus:' + msg);
                update_sitestatus(msg);
            });
            socket.on('func_init', function(msg) {
                d = JSON.parse(msg);
               console.log('function : ' + msg + ' initialized ');
               switch (d.func) {
                            case 'sitestatus':
                                cleardata('sitestatus');
                                showloading('site-loading');
                                socket.emit('func_init',msg)
                                break;
                            case 'm_status':
                                hidedata('m_status');
                                showloading('m-loading');
                                socket.emit('func_init',msg);
                                break;
                            case 'nodelist':
                                hidedata('nodelist');
                                showloading('node-loading');
                                socket.emit('func_init',msg);
                                break;
                            case 'salt_task_list':
                                socket.emit('func_init',msg);
                                break;
                            case 4:
                                
                                break;
                            case 5:
                                
                                break;
                            case 6:
                                break;
                            default:
                                 console.log('wrong function name');
                        } 

            });
            socket.on('status', function(msg) {
               // console.log('status:' + msg);
            });


            function update_menulist(m){
            msg = JSON.parse(m);
            console.log(msg);
            var newmlvalues ={
                jid: msg.jid,
                ml_title: msg.jid,
                ml_progress_info: msg.tgt + msg.msg,
                ml_info: msg.info,
                ml_progress: '<div style="width: '+ msg.progress+'%;"class="progress-bar progress-bar-'+msg.type+'"></div>'
              };
            switch (msg.msg){
                case 'started':
                    mltask += 1;
                    mlexec += 1;
                    menuList.add(newmlvalues);
                    break;
                case 'completed':
                    mlexec -= 1;
                    var mlitem = menuList.get('jid', msg.jid)[0];
                    mlitem.values(newmlvalues);
                default:
                    var mlitem = menuList.get('jid', msg.jid)[0];
                    mlitem.values(newmlvalues);
            }
            console.log(menuList.get('jid', msg.jid));
            
            document.getElementById('ml_task_counter').innerHTML = mlexec;
            document.getElementById('task_counter').innerHTML = ' You have '+mltask +' tasks. '+mlexec+' is running';
            };

            
            });
        </script>

        <div class="footer">
            <div class="pull-right">
                <a href="http://www.miibeian.gov.cn/" target="_blank" rel="nofollow"><strong>沪ICP备15006974号-2</strong></a>
            </div>
            <div>
                <strong>Copyright</strong> Deyun.io &copy; 2016-2017
            </div>
        </div>

        </div>
        </div>


   


   

</body>

</html>